### ISSUE TITLE
unselecting the selected items from dropdown

### ISSUE THREAD

**Issue by bharathkumareswaran** [rajush/ng-dropdown-multiselect#12]
I have used this dropdown in my application and it works well. But once my functionality is completed with the multi select, I want to remove the selection from the dropdown using code. I removed the items from the model and tried to make the selected property of the items to false in the config options. The model item array is made empty, but the selected icon on the dropdown doesn't go off. Can you please help me with the issue?

**Comment by rajush** [comment]
@bharathkumareswaran Do you have any example for this? May be a plunk or jsbin example with your scenario would be helpful

**Comment by rajush** [comment]
Closing this issue. 

Please re-open if issue persists.
