### ISSUE TITLE
Using this library with ui.bootstrap's dropdown got issue

### ISSUE THREAD

**Issue by harshalitalele** [rajush/ng-dropdown-multiselect#6]
Clicking on multiselect dropdown toggled another simple single select dropdown when it was put before multiselect dropdown.
I think there should be a specific selector inside 'angular-dropdown-multiselect' instead of '.dropdown-menu', something like '#dropdownMultiselect .dropdown-menu'.

This is probably not an issue, but I don't know where to put this forth.

**Comment by rajush** [comment]
@harshalitalele Do you have an example that replicates the issue? may be a plunk or something?

**Comment by rajush** [comment]
@harshalitalele oh you have a PR open... will try that out. Thanks
