### ISSUE TITLE
Pre-selected values

### ISSUE THREAD

**Issue by ws-gianni** [rajush/ng-dropdown-multiselect#9]
is it possible to select some values from the controller?  Thanks.

**Comment by rajush** [comment]
Currently it only does pre-select all from the controller. But that could be something as a new feature.

**Comment by rajush** [comment]
@ws-gianni The feature-request has been implemented now with the latest release to `v0.4.0`. Please go through the Readme file, as well as the demo here:
https://plnkr.co/edit/KpVqaiblOKGk5K6VWmi4?p=preview
